http:
  basePath: "/api/*"
  private:
    port: "8091"
  api:
    p-template-api:
      basePath: "/"
      host: ""
      port: ""
      path: ""  
autodiscovery:
  id: ""
  flow: "x-template-api-main"
  
scheduler:
  cron:
    expression: "0 0/15 * 1/1 * ? *"

cloudhub:
  domain: ""
  usrname: ""
  password: ""
  environment: ""
  
d365:
  host: "0.0.0.0"
  port: "8091"
  basepath: "/api"
  getPickOrders: "/pick/orders"
  updateOrderStatus: "/pick/orders/{route-id}"
  
jda:
  host: "0.0.0.0"
  port: "8091"
  basepath: "/api"
  postOrdersPath: "/orders"