http:
  basePath: "/api/v1/*"
  host: "0.0.0.0"
  private:
    port: "8091"
  consolePath: "/console/*"
  
api:
  discovery:
    id: ""
  
scheduler:
  cron:
    expression: "0 0/15 * 1/1 * ? *"
  
#----Common Block---No change Needed----      
cloudhub:
  username: "![5/w01nYmhxyvgHVC8Uh0yvTYk/WLHWBP2ZU+9DMOSnw=]"
  password: "![ae5QSfiTACKaB08EZlg0AA==]"
  
smtp:
  host: "mail.fatface.net"
  port: "465"
  user: "![5/w01nYmhxyvgHVC8Uh0yvTYk/WLHWBP2ZU+9DMOSnw=]"
  password: "![ae5QSfiTACKaB08EZlg0AA==]"
  subject: "Fatface API Exception"
#----Common Block---No change Needed----
  
d365:
  host: "mule-worker-internal-s-d365-api.ir-e1.cloudhub.io"
  port: "8091"
  basepath: "/api/v1"
  clientId: "587f052383c44efbadc76e22201cba19"
  clientSecret: "![+6LrbmEe+njbAiXUXZX1+7Nq1IMTLZTmBBLwyUF89jr5yQxXx6ydvM5v0UczJCgE]"
  dmf: 
    path: "/dmf/export"
    pick:
      create:
        definitionGroupId: "IDD009-PickRequest-Export"
        packageName: "Pick-Create-"
    export:
      orders:
        definitionGroupId: ""
        packageName: ""

  
  
jda:
  host: "mule-worker-internal-s-jda-data-int.ir-e1.cloudhub.io"
  port: "8092"
  basepath: "/api/v1"
  ordersPath: "/orders"
  clientId: "587f052383c44efbadc76e22201cba19"
  clientSecret: "![+6LrbmEe+njbAiXUXZX1+7Nq1IMTLZTmBBLwyUF89jr5yQxXx6ydvM5v0UczJCgE]"
  jks:
    password: "![Eiy80pOc3NMdDEvvqf5eTmUuYTIchkvpv2kk4Ge7Xv8=]"

lookup:
  host: "mule-worker-internal-sit-s-dblookup-api.ir-e1.cloudhub.io"
  port: "8091"
  basePath: "/api/v1"
  dbLookupPath: "/lookups"
  aptos:
    modeOfDelivery:
      key: "MODE_OF_DELIVERY-NUMSTR-APTOS"
    salesOfOrigin:
      key: "SALES_ORIGIN-MODE_OF_DELIVERY-APTOS"
    shippingBarcode:
      key: "SHIPPING_BAR_CODE-ORDERITEM_NUMSTR-APTOS"
  key: "ORDER_TYPE-MODE_OF_DELIVERY-D365"
  clientId: "587f052383c44efbadc76e22201cba19"
  clientSecret: "![+6LrbmEe+njbAiXUXZX1+7Nq1IMTLZTmBBLwyUF89jr5yQxXx6ydvM5v0UczJCgE]"
  queryParam:
    type: "ORDER_TYPE"
    catgeory: "MODE_OF_DELIVERY"
    source: "D365"
    aptos:
      modeOfDelivery:
        type: "MODE_OF_DELIVERY"
        category: "NUMSTR"
        source: "APTOS"
      salesOfOrigin:
        type: "SALES_ORIGIN"
        category: "MODE_OF_DELIVERY"
        source: "APTOS"
      shippingBarcode:
        type: "SHIPPING_BAR_CODE"
        category: "ORDERITEM_NUMSTR"
        source: "APTOS"
    
cron:
  expression: 
    manifest: "0 0/10 * 1/1 * ? *"
    orderextract: "0 0 * ? * * *"
    exportOrders:  ""    
   
orders:
  export:
    sftp:
      errorfilepath:  "/FatFace/sftp/MuleSoftIntegration/prod/error/outgoing/orderData/jdaOrder"
send:
  manifest:
    queue: "true"

pick:
  orders:
    orderType: "WEB"
  
report:
  host: "mule-worker-internal-s-reportdb-api.ir-e1.cloudhub.io"
  port: "8091"
  basepath: "/api/v1"
  clientId: "587f052383c44efbadc76e22201cba19"
  clientSecret: "![+6LrbmEe+njbAiXUXZX1+7Nq1IMTLZTmBBLwyUF89jr5yQxXx6ydvM5v0UczJCgE]"
  ordersPath: "/orders"
  
xcm:
  host: ""mule-worker-internal-s-xcm-api.ir-e1.cloudhub.io""
  port: "8091"
  basepath: "/api/v1"
  clientId: "587f052383c44efbadc76e22201cba19"
  clientSecret: "![+6LrbmEe+njbAiXUXZX1+7Nq1IMTLZTmBBLwyUF89jr5yQxXx6ydvM5v0UczJCgE]"
  salesOrdersPath: "/sales/orders"
  returnOrdersPath: "/return/orders"
  connecitonTimeout: "30000"

status:
  responseCode: "0"
  responseMessage: "Success"
  
pooling:
  profile:
    max:
      connection:
        size: "4"
      idle:
        size: "2"
      wait: "0"
