http:
  basePath: "/api/*"
  private:
    port: "8091"
  api:
    p-template-api:
      basePath: "/"
      host: ""
      port: ""
      path: ""  
autodiscovery:
  id: ""
  flow: "x-template-api-main"
  
scheduler:
  cron:
    expression: "0 0/15 * 1/1 * ? *"

cloudhub:
  domain: ""
  usrname: ""
  password: ""
  environment: ""
  
d365:
  host: "0.0.0.0"
  port: "8091"
  basepath: "/api"
  clientId: "1234"
  clientSecret: "4321"
  getPickOrders: "/pick/orders"
  
  
jda:
  host: "0.0.0.0"
  port: "8081"
  basepath: "/api/v1"
  postOrdersPath: "/orders"
  clientId: "1234"
  clientSecret: "4321"
  jks:
    password: "![bQO6YOBaGgBfhDsXXTHEPw==]"
  
lookup:
  host: "0.0.0.0"
  port: "8091"
  basePath: "/api"
  dbLookupPath: "/lookups"
  key: "ORDER_TYPE-MODE_OF_DELIVERY-D365"
  clientId: "1234"
  clientSecret: "4321"
  queryParam:
    type: "ORDER_TYPE"
    catgeory: "MODE_OF_DELIVERY"
    source: "D365"