autodiscovery:
  id: ""
  flow: "b-order-mgmt-app"
  
scheduler:
  cron:
    expression: "0 0/15 * 1/1 * ? *"

cloudhub:
  domain: ""
  usrname: ""
  password: ""
  environment: ""
  
d365:
  host: "0.0.0.0"
  port: "8091"
  basepath: "/api/v1"
  clientId: "b206a1a7bfbd4e109f591ca5b27631c3"
  clientSecret: "2Cf50B5970B14FC9a94D5aB48Fad1206"
  pickOrdersPath: "/pick/orders"
  
  
jda:
  host: "0.0.0.0"
  port: "8092"
  basepath: "/api/v1"
  ordersPath: "/orders"
  clientId: "b206a1a7bfbd4e109f591ca5b27631c3"
  clientSecret: "2Cf50B5970B14FC9a94D5aB48Fad1206"
  jks:
    password: "![Eiy80pOc3NMdDEvvqf5eTmUuYTIchkvpv2kk4Ge7Xv8=]"
  
lookup:
  host: "0.0.0.0"
  port: "8091"
  basePath: "/api/v1"
  dbLookupPath: "/lookups"
  key: "ORDER_TYPE-MODE_OF_DELIVERY-D365"
  clientId: "1234"
  clientSecret: "4321"
  queryParam:
    type: "ORDER_TYPE"
    catgeory: "MODE_OF_DELIVERY"
    source: "D365"