#%RAML 1.0 DataType
displayName: Transfer orders fields
type: object
properties:
  TransferNumber: string  
  LineNumber: string  
  Barcode: string
  Colour: string
  FromWarehouse: string  
  ItemId: string
  LineReceiptDate: string
  LineShipDate: string
  ReceiptDate: string
  ReceivedQty: string
  ReceiveRemain: string
  Remaining: string
  ShipDate: string
  ShippedQty: string
  Size: string
  Style: string
  ToWarehouse: string
  TransformOrderStatus: string
  TransferQty: string
  
  
  