#%RAML 1.0 DataType
displayName: Transfer Shipped order dataheader fields
type: object
properties:
  record-type: string  
  tag-id: string  
  user-def-note-1: string
  shipped-dstamp: string
  user-def-type-1?: string  
  sku-id: string
  qty-shipped: string