#%RAML 1.0 DataType
displayName: Shipped order dataheader fields
properties:
  record-type: string
  action?: string
  client-id?: string
  order-id?: string
  line-id?: string
  sku-id: string
  batch-id?: string
  expiry-dstamp?: string
  config-id?: string
  tag-id: string
  work-group?: string
  consignment?: string
  container-id?: string
  pallet-id?: string
  pallet-config?: string
  site-id?: string
  location-id?: string
  owner-id?: string
  qty-picked?: string
  picked-dstamp?: string
  qty-shipped: string
  shipped-dstamp: string
  shipped?: string
  station-id?: string
  user-id?: string
  pallet-volume?: string
  pallet-height?: string
  pallet-depth?: string
  pallet-width?: string
  pallet-weight?: string
  receipt-id?: string
  receipt-dstamp?: string
  supplier-id?: string
  origin-id?: string
  condition-id?: string
  lock-status?: string
  lock-code?: string
  notes?: string
  manuf-dstamp?: string
  trailer-id?: string
  bol-id?: string
  user-def-type-1?: string
  user-def-type-2?: string
  user-def-type-3?: string
  user-def-type-4?: string
  user-def-type-5?: string
  user-def-type-6?: string
  user-def-type-7?: string
  user-def-type-8?: string
  user-def-chk-1?: string
  user-def-chk-2?: string
  user-def-chk-3?: string
  user-def-chk-4?: string
  user-def-date1?: string
  user-def-date2?: string
  user-def-date3?: string
  user-def-date4?: string
  user-def-num-1?: string
  user-def-num-2?: string
  user-def-num-3?: string
  user-def-num-4?: string
  user-def-note-1: string
  user-def-note-2?: string
  time-zone-name?: string
  spec-code?: string
  qty-delivered?: string
  delivered-dstamp?: string
  delivered?: string
  pod-confirmed?: string
  pod-exception-reason?: string
  trailer-position?: string
  kit-ratio?: string
  from-label?: string
  to-label?: string
  pack-despatch-repack?: string
  uploaded?: string
  uploaded-vview?: string
  sap-tid?: string
  sap-pick-id?: string
  sap-pick-req?: string
  ce-rotation-id?: string
  ce-consignment-id?: string
  ce-receipt-type?: string
  ce-originator?: string
  ce-originator-reference?: string
  ce-coo?: string
  ce-cwc?: string
  ce-ucr?: string
  ce-under-bond?: string
  ce-document-dstamp?: string
  customer-id?: string
  pick-label-id?: string
  ce-duty-stamp?: string
  catch-weight?: string
  shipment-number?: string
  picked-weight?: string
  picked-volume?: string
  tracking-level?: string
  archived?: string
  carrier-id?: string
  hub-carrier-id?: string
  hub-service-level?: string
  service_level?: string
  proforma-invoice-num?: string
  carrier-container-id?: string
  container-weight?: string
  container-height?: string
  container-width?: string
  container-depth?: string
  packing-pallet-qty?: string
  packing-pallet-type?: string
  container-type?: string
  container-n-of-n?: string
  hub-container-id?: string
  labelled?: string
  reprint-labels?: string
  status?: string
  pallet-labelled?: string
  load-sequence?: string
  ce-order-id?: string
  ce-status?: string
  ce-reason-notes?: string
  ce-instructions?: string
  uploaded-customs?: string
  customer-shipment-number?: string
  shipment-group?: string
  master-order-id?: string
  master-order-line-id?: string
  shipment-ref?: string
  carrier-consignment-num?: string
  carrier-consignment-id?: string
  total-volume?: string
  trolley-slot-id?: string
  carrier-manifest-number?: string
  transport-boxes?: string