#%RAML 1.0 NamedExample
  customer-id: "9991331068"
  fullname: "Nicola Carbis"
  first-name: "Nicola"
  last-name: "Carbis"
  telephone: "07905339295"
  email: "carbis1@btinternet.com"
  shipping-address: !include shipping-address.raml