#%RAML 1.0 NamedExample
first-name: "sfsrfer"
last-name: "dscsdc"
street: "29-30 Market Place"
city: "hexham"
postcode: "NE46 3pb"
state: "Northumberland"
country: "Great Britain"
contact-number: "11111111111"