#%RAML 1.0 NamedExample
  - - record-type: "MAN"
      action: "E"
      client-id: "FATFACE"
      order-id: "34786480"
      line-id: "4403"
      sku-id: "505275220194"
      config-id: "40E1C"
      tag-id: "T0026192189"
      work-group: "WAVE04"
      consignment: "211"
      container-id: "62827011"
      pallet-id: "G704934"
      pallet-config: "PALLET"
      site-id: "PICK"
      location-id: "STORESHIP"
      owner-id: "FATFACE"
      qty-picked: "1.000000"
      picked-dstamp: "20201209112705"
      qty-shipped: "1.000000"
      shipped-dstamp: "20201209163707"
      shipped: "Y"
      station-id: "W258319"
      user-id: "131"
      pallet-volume: "1.001139"
      pallet-height: "0.000000"
      pallet-depth: "0.000000"
      pallet-width: "0.000000"
      pallet-weight: "0.000000"
      receipt-id: "34637736"
      receipt-dstamp: "20201104075848"
      supplier-id: "KANIKA"
      lock-status: "UnLocked"
      user-def-type-1: "956677"
      user-def-type-2: "GRY-STEEL"
      user-def-type-3: "-"
      user-def-type-4: "10"
      user-def-type-5: "POLAR BEAR CLASSIC PANT"
      user_def_chk_1: "N"
      user_def_chk_2: "N"
      user_def_chk_3: "N"
      user_def_chk_4: "N"
      user_def_num_1: "0.000000"
      user_def_num_2: "0.000000"
      user_def_num_3: "0.000000"
      user_def_num_4: "0.000000"
      time_zone_name: "Europe/London"
      qty_delivered: "0.000000"
      delivered: "N"
      pod_confirmed: "N"
      kit_ratio: "1.000000"
      from_label: "0"
      to_label: "0"
      uploaded: "N"
      uploaded_vview: "N"
      sap_tid: null
      sap_pick_id: "0"
      ce_rotation_id: "XX/D00000001"
      ce_receipt_type: "NB"
      ce_under_bond: "N"
      customer_id: "CANTERBURY 2"
      pick_label_id: "36131459"
      ce_duty_stamp: "N"
      catch_weight: "0.000000"
      shipment_number: "5111649"
      picked_weight: "0.000000"
      picked_volume: "0.000025"
      tracking_level: "E"
      archived: "N"
      container_weight: "0.000000"
      container_height: "1.000000"
      container_width: "1.000000"
      container_depth: "1.000000"
      packing_pallet_qty: "0"
      container_type: "CONT"
      container_n_of_n: "0"
      status: "Open"
      uploaded_customs: "Y"
      customer_shipment_number: "0"
      master_order_line_id: "0"
      carrier_consignment_num: "0"
      total_volume: "0.000000"
      trolley_slot_id: "0"     
      transport_boxes: "0"