#%RAML 1.0 NamedExample
  transfer-number: "IDD040-0013"  
  line-number: 1  
  sku-id: "8223481923190"
  colour: "BLUE"
  from-warehouse: "70462"  
  item-number: "AB_SHIRT01"
  line-receipt-date: "2021-06-01T00:00:00"
  line-ship-date: "2021-06-01T00:00:00"
  receipt-date: "2021-01-06T00:00:00"
  received-qty: "0.000000"
  receive-remain: "1.000000"
  remaining: "Receiving"
  shipped-date: "2021-01-06T00:00:00"
  shipped-qty: "1.000000"
  size: "L"
  style: "SLIM"
  to-warehouse: "70012"
  transform-order-status: "Shipped"
  transfer-qty: "1.000000"
  location: "LIT"