#%RAML 1.0 NamedExample
  item-id: "1"
  item-name: "RUBY LEAF SCHIFFLEY LONGLINE WHT-WHITE 6 9EWA"
  sales-price: 39.98
  barcode: "5052751553606"
  quantity: 1.23
  amount: 39.45
  tax-amount: 1.39
  tax-rate: 20.5
  