#%RAML 1.0 NamedExample
    order-no: "28759577"
    order-date: 2019-10-03T18:25:43.200Z
    currency: "GBP"
    language: "en-gb"
    source: "APTOS"
    delivery-mode: "1"
    legal-entity: "1FFL"
    store: !include store.raml
    customer: !include customer.raml
    orderlines: [!include orderline.raml]
    payments: [!include payment.raml]