#%RAML 1.0 NamedExample
  item-id: "1"
  item-name: "RUBY LEAF SCHIFFLEY LONGLINE WHT-WHITE 6 9EWA"
  sales-price: 39.5
  barcode: "5052751553606"
  quantity: 1.0
  amount: 39.5
  tax-amount: 1.98
  tax-rate: 20.0101
  