#%RAML 1.0 NamedExample
season: "7GMA"
qualifier: "928883"
tarrif-code: "6110209900"
country-id: "X"
name: "CASHMERE ZIP THROUGH"
retail-type: "MENS"
product-type: "KNITWEAR"
product-category: "JUMPERS"
is-active: true
skus: [!include sku.raml]
product-id: "AB3"
status: "LIVE"