#%RAML 1.0 DataType
displayName: Transfer orders fields
type: object
properties:
  record-type?: string  
  tag-id?: string  
  user-def-note-1?: string
  user-def-type-1?: string 
  region?: string
  transfer-number?: string  
  line-number: number  
  sku-id: string
  colour?: string
  from-warehouse?: string  
  item-number: string
  line-receipt-date?: string
  line-ship-date?: string
  receipt-date?: string
  received-qty?: string
  receive-remain?: string
  remaining?: string
  shipped-date: string
  shipped-qty: string
  size?: string
  style?: string
  to-warehouse: string
  transform-order-status?: string
  transfer-qty?: string