#%RAML 1.0 DataType
displayName: Transfer orders fields
type: object
properties:
  record-type: 
    description: Record type of the item
    type: string
    required: false
  tag-id:   
    description: Tag id of the item
    type: string
    required: false
  region: 
    description: Region value is based on UK or US
    type: string
    required: false
  transfer-number: 
    description: Number transferred based on the region uk or us
    type: string
    required: false  
  line-number: 
    description: Sequence number of items of a particular order
    type: number
    required: true  
  sku-id: 
    description: Barcode id of the item
    type: string
    required: true
  colour: 
    description: Colour of the item
    type: string
    required: false
  from-warehouse: 
    description: This is the from warehouse of the item
    type: string
    required: false  
  item-number: 
    description: Item number also referred as user-def-type-1
    type: string
    required: true
  line-receipt-date: 
    description: Line received date of the item
    type: string
    required: false
  line-ship-date: 
    description: Line shipped date of the item
    type: string
    required: false
  receipt-date: 
    description: Receipt date of the item
    type: string
    required: false
  received-qty: 
    description: Quantity received
    type: string
    required: false
  receive-remain: 
    description: Receive remain
    type: string
    required: false
  remaining: 
    description: Remaining receive updated
    type: string
    required: false
  shipped-date: 
    description: Shipped date of the item
    type: string
    required: true
  shipped-qty: 
    description: Quantity shipped
    type: string
    required: true
  size: 
    description: Size of the item
    type: string
    required: false
  style: 
    description: Style of the item
    type: string
    required: false
  to-warehouse: 
    description: to-warehouse of the item which is also referred as user-def-note-1
    type: string
    required: true
  transform-order-status: 
    description: This is to transfer the order status as Shipped or Received
    type: string
    required: false
  transfer-qty: 
    description: Quantity transferred
    type: string
    required: false