#%RAML 1.0 DataType
type: object
displayName: inventory
properties:
  client-id?: string
  record-type?: string
  action?: string
  code?: string,
  orig-qty-sign?: string
  orig-qty?: string,
  updt-qty-sign?: string
  updt-qty?: string
  created-date?: datetime-only
  sku?:
  type: !include sku.raml        
  from-loc-id?: string
  to-loc-id?: string
  final-loc-id?: string
  reference-id?: string
  line-id?: string
  notes?: string
  reason-id?: string
  user-id?: string
  site-id?: string
  owner-id?: string
  lock-code?: string
  lock-status?: string
  session-type?: string
  