#%RAML 1.0 DataType
type: object
displayName: sample
properties:
  companyNumber?: integer
  documentType?: string
  documentNumber?: integer
  mobilisation?: number
  status?: string
  onHireDate?: date-only
  offHireDate?: date-only
  itemDescription?: string
  siteName?: string
  postcode?: string
  expirationDate?: date-only

